[[main]]
  name = "ホーム"
  pageRef = "/"
  weight = 10

[[main]]
  name = "株式投資"
  pageRef = "categories/株式投資"
  weight = 20

[[main]]
  name = "FX・為替"
  pageRef = "categories/fx"
  weight = 30

[[main]]
  name = "経済ニュース"
  pageRef = "categories/経済ニュース"
  weight = 40

[[main]]
  name = "資産形成"
  pageRef = "categories/資産形成"
  weight = 50

[[main]]
  name = "記事一覧"
  pageRef = "posts"
  weight = 60

[[footer]]
  name = "プライバシーポリシー"
  pageRef = "privacy"
  weight = 10

[[footer]]
  name = "お問い合わせ"
  pageRef = "contact"
  weight = 20
